# Generated by Django 5.0.3 on 2024-04-03 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='03/11/24'),
        ),
    ]
